name: Build and Test

on:
  push:
    branches: [ main ]
  
jobs:
  unit-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Change directory
        run: cd circom-starter

      - name: Install dependencies
        run: yarn install

      - name: Build circuits
        run: yarn circom:dev

      - name: Test
        run: yarn test 

    