name: Build and Test

on:
  push:
    branches: [ main ]
  
jobs:
  unit-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
        submodules: recursive

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install
        working-directory: circom-starter

      - name: Build circuits
        run: yarn circom:dev
        working-directory: circom-starter

      - name: Test
        run: yarn test 
        working-directory: circom-starter

    