name: Build and Run

on:
  push:
    branches: [ main, dev ]
  
jobs:
  run-mpc:
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install
        working-directory: mpc-phase2

      - name: Install dependecies for cli
        run: yarn install
        working-directory: mpc-phase2/phase2cli

      - name: Build
        run: yarn build
        working-directory: mpc-phase2/phase2cli

      - name: Auth
        run: yarn auth 
        working-directory: mpc-phase2/phase2cli


    