name: Build and Run

on:
  push:
    branches: [ main ]
  
jobs:
  unit-tests:
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Change directory
        run: cd mpc-phase2

      - name: Install dependencies
        run: yarn install

      - name: Change dir
        run: cd phase2cli 

      - name: Dependencies again
        run: yarn install

      - name: Test
        run: yarn auth 

    